global using System.Collections.Immutable;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using UnoIconBug.DataContracts;
global using UnoIconBug.DataContracts.Serialization;
global using UnoIconBug.Models;
global using UnoIconBug.Presentation;
global using UnoIconBug.Services.Caching;
global using UnoIconBug.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
